### ISSUE TITLE
Compatibilidade com o American Truck Simulator

### ISSUE THREAD

**Issue by olecr4n** [davidsantos-br/ETS2Sync-Helper-4#1]

**Comment by DaviMedrade** [comment]
Sim, pretendo fazer isso quando tiver mais tempo. Infelizmente o pessoal do atssync.de não disponibilizou uma API (ou não tinha na última vez que pesquisei a respeito) então eu teria que descobrir como gerar minha própria lista de cargas.

**Comment by olecr4n** [comment]
show!!! com o teu sincronizador no ets já ficou muito melhor jogar no mp, no ats ia ser bacana também!!! continua como o bom trabalha pra comunidade que curte esse tipo de jogo!!! :) abrçs

**Comment by DaviMedrade** [comment]
Veja #6.
