### ISSUE TITLE
Não estou conseguindo sincronizar: ERRO HTTP 426 Upgrade Required.

### ISSUE THREAD

**Issue by DiegoSi** [davidsantos-br/ETS2Sync-Helper-4#14]
**Davidsantos-br
hoje dia 16/06/2017 tentei fazer a sincronização das cargas, mais apareceu o seguinte erro: HTTP 426 Upgrade Required. Estou com a ultima versão do jogo, e tenho todas as dlcs. estou usando a versão 5.1.0.0 do aplicativo. segue imagem. consegue me ajudar ?
![ets2](https://user-images.githubusercontent.com/29492811/27244499-29fbabf4-52bd-11e7-98b8-1fb82806b2ea.jpg)
 em anexo.

**Comment by JhowDroid** [comment]
@DiegoSi, A versão mais recente saiu dia 14/06/17, a mensagem diz que você precisa baixar a nova versão que é 5.2.0

**Comment by DiegoSi** [comment]
Boa noite. em qual site eu baixo a versão atualizada

?

**Comment by DaviMedrade** [comment]
http://files.dsantosdev.com/ets2sync_helper.zip
