### ISSUE TITLE
Error: Unfortunately, binary saves aren't supported yet. Please create the save using a text format.

### ISSUE THREAD

**Issue by serenorj** [davidsantos-br/ETS2Sync-Helper-4#15]
unfortunately bynare saves are not yet supported yet please create the save using test format

**Comment by davidsantos-br** [comment]
*Versão em português abaixo.*

1. Close the game.
2. Open ETS2Sync Helper. If you're playing ATS, select “ATS” in the “Game” option.
3. In the panel “Game Settings” there is a line saying “Save Format: Binary - Set to ‘Text’”. Click “Set to ‘Text’”.
4. When the message turns green and says “Save Format: Text”, you can open the game and create a new save for syncing.

The problem with this method is that it keeps the save format set to “Text”, which makes the game freeze for a second when it's creating an autosave (i.e. once every five or ten minutes). If you want to avoid that, use the method below:

1. Enable the game's Developer Console (if it's already enabled, skip to step 2).
    1. Close the game.
    2. Open ETS2Sync Helper. If you're playing ATS, select “ATS” in the “Game” option.
    3. In the “Game Settings” panel, there is a line saying “Settings Folder: <folder with your ETS2/ATS settings> - Options”. Click “Options” → “Open game config file”. A Notepad window will appear, with the game settings file open.
    4. In that Notepad window, go to “Edit” → “Find…” (or hit Ctrl+F). In the search window, type `g_developer` and hit Enter. It should highlight a line in the file that reads `uset g_developer "0"`. Change that `0` to `1`, so that it reads `uset g_developer "1"`.
    5. Go to “Edit” → “Find…” (or hit Ctrl+F) again. In the search window, type `g_console` and hit Enter. It should highlight a line in the file that reads `uset g_console "0"`. Change that `0` to `1`, so that it reads `uset g_console "1"`.
    6. Save the file and close Notepad.
2. Open the game.
3. When you're ready to sync, open the Console (use the key above `Tab`, to the left of the `1` key in the alphanumeric keyboard).
4. In the Console, type `g_save_format 2` and hit Enter.
5. Save, sync, load the save.
6. In the Console, type `g_save_format 0` and hit Enter.

If you choose this method (which I recommend), you'll have to repeat steps 4, 5, and 6 every time you sync. If you're driving and the game suddenly freezes for a second every five or ten minutes, you probably forgot to do step 6. You don't need to sync again, just open the console and do step 6.

**Comment by davidsantos-br** [comment]
*English version above.*

1. Feche o jogo.
2. Abra o ETS2Sync Helper. Se estiver jogando ATS, selecione “ATS” na opção “Game”.
3. No quadro “Game Settings” há uma linha dizendo “Save Format: Binary - Set to ‘Text’”. Clique em “Set to ‘Text’”.
4. Quando a mensagem ficar verde e dizer “Save Format: Text”, você pode abrir o jogo e criar um novo save para sincronizar.

O problema com esse método é que ele mantém o formato do save como “Texto”, o que faz o jogo travar por um segundo quando estiver criando um autosave (i.e. a cada cinco ou dez minutos). Se você quiser evitar isso, use o método abaixo:

1. Ative o Console de Desenvolvimento do jogo (se já estiver ativado, pule para o passo 2).
    1. Feche o jogo.
    2. Abra o ETS2Sync Helper. Se estiver jogando ATS, selecione “ATS” na opção “Game”.
    3. No quadro “Game Settings”, há uma linha dizendo “Settings Folder: <pasta de configuração do ETS2/ATS> - Options”. Clique em “Options” → “Open game config file”. Uma janela do Bloco de Notas vai aparecer, com o arquivo de configurações do jogo aberto.
    4. Nessa janela do Bloco de Notas, vá em “Editar” → “Localizar…” (ou tecle Ctrl+F). Na janela de busca, digite `g_developer` e tecle Enter. Isso deve destacar uma linha que diz `uset g_developer "0"`. Troque o `0` por `1`, para que fique `uset g_developer "1"`.
    5. Vá em “Editar” → “Localizar…” (ou tecle Ctrl+F) novamente. Na janela de busca, digite `g_console` e tecle Enter. Isso deve destacar uma linha que diz `uset g_console "0"`. Troque o `0` por `1`, para que fique `uset g_console "1"`.
    6. Salve o arquivo e feche o Bloco de Notas.
2. Abra o jogo.
3. Quando estiver pronto para sincronizar, abra o Console (use a tecla acima do `Tab`, à esquerda do `1` no teclado alfanumérico).
4. No Console, digite `g_save_format 2` e tecle Enter.
5. Salve, sincronize, carregue o save.
6. No Console, digite `g_save_format 0` e tecle Enter.

Se você escolher este método (o que eu recomendo), você vai ter que repetir os passos 3, 4, 5, e 6 todas as vezes que for sincronizar. Se você estiver dirigindo e o jogo travar de repente por um segundo a cada cinco ou dez minutos, você provavelmente esqueceu de fazer o passo 6. Não é necessário sincronizar novamente, apenas abra o Console e faça o passo 6.

**Dica:** No Console, pressione `↑` (seta para cima) para digitar novamente os últimos comandos que você usou. Por exemplo, no passo 4 você usa o comando `g_save_format 2`, então no passo 6 em vez de digitar tudo novamente você pode simplesmente apertar `↑` e trocar o `2` por `0` antes de dar Enter.

**Comment by DaviMedrade** [comment]
English: 
https://github.com/davidsantos-br/ETS2Sync-Helper-4/blob/master/README.md#unfortunately-binary-saves-arent-supported-yet-please-create-the-save-using-a-text-format

Português:
https://github.com/davidsantos-br/ETS2Sync-Helper-4/blob/master/README-pt.md#unfortunately-binary-saves-arent-supported-yet-please-create-the-save-using-a-text-format
