### ISSUE TITLE
ATS version 1.28 is broken

### ISSUE THREAD

**Issue by USAFKY** [davidsantos-br/ETS2Sync-Helper-4#19]
First of all let me say THANKS for the program and your efforts to keep it current.

The current version of ATS only has 1 job in freight and quick jobs from fresno to Elko.
That all ONLY 1 job...contract seems to remain the same.

The only fix we are using is in your current profile change g_force economy  from "0" to "1", that loads jobs to choose from but not synced.

Thank you sir...please advise.

**Comment by DaviMedrade** [comment]
Regarding g_force_economy_reset, you can just use the button “Economy Reset” instead of “Sync” in the app and when you load the save the economy will be reset the same way.

Regarding support for 1.28, I'm still working on it but it's not finished yet. See #17.
