### ISSUE TITLE
Erro ao abrir V4.0

### ISSUE THREAD

**Issue by losfacto** [davidsantos-br/ETS2Sync-Helper-4#2]
"O programa não pode ser iniciado porque está faltando MSVCP140.dll no seu computador. Tente reinstalá-lo para resolver esse problema."

"O programa não pode ser iniciado porque está faltando VCRUNTIME140.dll no seu computado. Tente reinstala bla bla bla..."

O que sera? é só no meu?

**Comment by DaviMedrade** [comment]
Hmm. Estranho, isso não deveria ser necessário. Vou revisar as configurações de compilação. Nesse meio-tempo, você pode instalar essas DLLs usando o instalador fornecido pela Microsoft:

https://www.microsoft.com/pt-BR/download/details.aspx?id=48145

**Comment by losfacto** [comment]
Ok obrigado pela Atenção Davi

Em sábado, 22 de outubro de 2016, David Santos notifications@github.com
escreveu:

**Comment by DaviMedrade** [comment]
Lançada a versão 4.0.1, com a CRT linkada estaticamente no executável. Com essa versão não deve ser necessário instalar o VC++ 2015 runtime.

**Comment by losfacto** [comment]
Valeu muito obrigado

Em quarta-feira, 26 de outubro de 2016, David Santos <
notifications@github.com> escreveu:
