### ISSUE TITLE
New Mexico/Italy/Special Transport DLCs

### ISSUE THREAD

**Issue by Dragon951** [davidsantos-br/ETS2Sync-Helper-4#25]
Hello,

Currently with the NEW ATS Update and the new mexico dlc, the sync program is not showing any jobs towards the new DLC, would you be able to update the sync program to work with American truck simulatir version 1.29 with New Mexico DLC??

**Comment by DaviMedrade** [comment]
Yes, but it will take a few days.

**Comment by wolf0958** [comment]
Any word on updating the program to work with the New Mexico DLC for ATS ?? It doesn't show jobs for that State

**Comment by Dragon951** [comment]
Hello,

I just wanted to see the Status Of this update

I would also like to announce the new Italia DLC is out and the sync would have to be updated to work with that as well please and thank you

Thanks for your hard word and dedication :) 👍

**Comment by Dragon951** [comment]
Just wanted to inform you another DLC has just came out for Euro Truck Simulator 2 special transport cargo

**Comment by DaviMedrade** [comment]
Personal issues have prevented me from dealing with this. A new version should be released in the first or second week of January.

**Comment by DaviMedrade** [comment]
I finally managed to get the new DLCs and now I have some free time. Assuming no unexpected complications, the new version should be released within a few hours.

**Comment by DaviMedrade** [comment]
I mean, if Steam ever finishes its updates. I have been using my Windows 7 partition lately, so I haven't booted this Windows 10 partition (where I have my development environment set up) in weeks. That plus the new DLCs means a few gigabytes in updates before I can really start working. Good thing I only have 5 games on Steam. 😛

**Comment by DaviMedrade** [comment]
Apparently this will take one more day. I'm running maintenance tasks on Windows so I can work on the update without my hard drive constantly at 100% activity, but they are taking a long time. I started working on the update at around midnight, and by 3am I gave up because things were running so slowly and started troubleshooting Windows. It's now 8:30am and it isn't done yet. I need some sleep, so I'll let Windows do its thing in the meantime and come back to it later.

**Comment by DaviMedrade** [comment]
OK, Windows is done updating and defragging. Unfortunately, it seems to have removed my Windows 7 boot from the boot menu, but that's an issue for another time. Now I can get back to preparing this update.

**Comment by DaviMedrade** [comment]
Hmm. I have to go out now. And that's just after I noticed a “Game Change Detected” issue for people who have Italia but not Schwarzmüller. Isolating the job(s) causing this to figure out the problem can take a while.

**Comment by wolf0958** [comment]
Thanks for the update David. My friends and I are looking forward to the new version that includes New Mexico for ATS.. Great program. Keep up the great work my friend.
