### ISSUE TITLE
SYNCHRONIZATION PROBLEM DLC ITALIA,

### ISSUE THREAD

**Issue by DiegoSi** [davidsantos-br/ETS2Sync-Helper-4#26]
**David, good night,
I am not able to synchronize the loads on the map of italy, do you have any position on when it will leave new update of the application? Already taking advantage of the new update of special loads that was launched today. thank you for your david work, without it we do not have the same fun in the game in multiplayer mode.**

**Comment by davidsantos-br** [comment]
Duplicate of #25.

**Comment by DaviMedrade** [comment]
Duplicate of #25
