### ISSUE TITLE
Erro 503 Service Temporarily Unavailable ao sincronizar

### ISSUE THREAD

**Issue by johnwct2014** [davidsantos-br/ETS2Sync-Helper-4#3]
quando vou sincronizar o programa da erro ao sincronizar a carga

**Comment by DaviMedrade** [comment]
O site de onde é feito o download da lista de cargas, ets2sync.com, saiu do ar. Se não voltar em alguns dias, eu vejo outra forma de obter ou gerar uma lista de cargas.

**Comment by johnwct2014** [comment]
ok vlw ae


________________________________
De: David Santos <notifications@github.com>
Enviado: terça-feira, 20 de dezembro de 2016 12:39
Para: davidsantos-br/ETS2Sync-Helper-4
Cc: johnwct2014; Author
Assunto: Re: [davidsantos-br/ETS2Sync-Helper-4] Erro 503 Service Temporarily Unavailable ao sincronizar (#3)


O site de onde é feito o download da lista de cargas, ets2sync.com, saiu do ar. Se não voltar em alguns dias, eu vejo outra forma de obter ou gerar uma lista de cargas.

-

**Comment by j1m1l0k0** [comment]
Faz um arquivo joblist local mano... é mais seguro

**Comment by FOX-TROT9993** [comment]
Como assim joblist local

**Comment by johnwct2014** [comment]
como assim?

**Comment by DaviMedrade** [comment]
“arquivo joblist local” = criar minha própria lista de cargas em vez de usar uma de outro site

Na verdade é exatamente isso que eu pretendo fazer, o que vai trazer duas vantagens: suporte à DLC Vive La France! e suporte ao American Truck Simulator.

**Comment by DaviMedrade** [comment]
Coloquei uma lista de cargas, mas ela é fixa. Preciso criar mais algumas e dar um jeito de fazer com que o servidor alterne entre elas (tipo, uma por semana como o ets2sync.com fazia).

Quanto ao ATS e à DLC da França, veja #6.

**Comment by j1m1l0k0** [comment]
Isso mano,  sua lista de cargas baseada nas já existentes pra não ter que reinventar a roda ;)

criar um joblist dentro do seu programa sem a necessidade de baixar via HTTP é muito mais seguro e caso haja atualização, ela seja feita daqui mesmo direto do github (que provavelmente nunca sairá do ar)
