### ISSUE TITLE
Weekly List update change date ?

### ISSUE THREAD

**Issue by djlesley93** [davidsantos-br/ETS2Sync-Helper-4#30]
is it possibla to change the date to sunday ? now it is Wednesday is this possibla ?

**Comment by DaviMedrade** [comment]
I'd rather keep it on Tuesday or Wednesday, people still play a lot on Sunday night, and I wouldn't want the list changing right in the middle of it. It's worth noting that the change happens at midnight UTC, so in California, for example, it would still be 17:00 (5pm). Here in São Paulo it would still be 21:00. I wouldn't want the list changing at those times on a Sunday.
