### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by Alexr03** [davidsantos-br/ETS2Sync-Helper-4#36]
I have followed everything in the readme and I am still unable to sync my job, I load up my saved game after clicking "Sync Jobs" and it returns successful. Except when I get in-game it tells my my game was changed and it was moved to the garage, I check the Market list and the jobs wasn't synced.

Any ideas? Thanks.

**Comment by Alexr03** [comment]
=Update=
If I choose no DLC's, the jobs will sync.
I went on to choose each DLC one by one, and if I choose Scandinavia DLC, it will break and not sync the jobs however choosing all other DLC's will work fine! https://i.Alexr03.com/Vk995gp9282y.png

**Comment by MikadoSTL** [comment]
I am have the same problem, so it is not just you.

**Comment by Thomasdavid097** [comment]
still working fine for me, been using it mostly everyday
