### ISSUE TITLE
ETS2 & ATS V. 1.32

### ISSUE THREAD

**Issue by Dragon951** [davidsantos-br/ETS2Sync-Helper-4#38]
Hello,

With Multiplayer still down, i still wanted to get this ticket going so the program is updated sooner rather than later, So with the 1.32 Update, you can now own your own trailer, with that being said, the program has to be updated to be able to include jobs for personal trailers as well, 

Would it be possible to get the next update going as soon as you can?

**Comment by Bas950** [comment]
1.32 is now out for TMP but we cant sinc! Please fix!

**Comment by wolf0958** [comment]
Yes please update sync helper. It no longer works since 1.32 update. Any word when a fix may be coming.. Thanks

**Comment by disto1978** [comment]
First of all guys, this is a free tool developed in free time, so stop demand an update but ask nicely and be grateful;) Finally I would like to join the request for an 1.32 compatible Update including the new freight market for own trailers.

**Comment by DaviMedrade** [comment]
I don't know when I'll be able to update the app because I've been pretty busy and I don't know how much work it will take to get it to work with the new trailer ownership feature.

In any case, there's no point in updating it now only to have to update it again after the Oregon DLC is released.

**Comment by kogle130** [comment]
Better doing it propper before quick and buggy i agree.
Just remeber there are a few thousand players counting on you:-)
No serious thank you! I really appreciate your tool a lot!!

**Comment by j1m1l0k0** [comment]
> I don't know when I'll be able to update the app because I've been pretty busy and I don't know how much work it will take to get it to work with the new trailer ownership feature.
> 
> In any case, there's no point in updating it now only to have to update it again after the Oregon DLC is released.

Se quiser ajuda para atualiza-lo avisa aae ;)

**Comment by j1m1l0k0** [comment]
@davidsantos-br se quiser ajuda para atualiza-lo avisa aí.  Acredito que não seja no fonte do projeto que terá que atualizar e sim no arquivo script de carga correto ?

**Comment by wolf0958** [comment]
Any word when update may be coming.??. This is a great program

**Comment by typ431127** [comment]
期待你的更新

**Comment by j1m1l0k0** [comment]
let's help update the synchronizer.

**Comment by Marcelokash** [comment]
Boa noite Senhores gostaria de saber quando sera liberado a atualização do app.
Good evening, ladies and gentlemen, I'd like to know when the app update will be released.

**Comment by Leassus** [comment]
can we assume this project is dead?

**Comment by CiprianN23** [comment]
@Leassus It would be dead if the owner(davidsantos-br) wouldnt answer to this issue but he did. But as he said he has his personal life and cant work only on this project so we can expect to be no updates for a while.

But this project is open-source so anyone with skills in C++ can update it(i know for sure david will check the changes and accept them) 

Edit: Also can be redone in other programing language not really C++ (advance things)

**Comment by wolf0958** [comment]
David. This program is great and is missed by a great number of users. I can understand real life and commitments. We are all just wondering if the program is going to be updated to work with version 1.32. We all understand also it takes working with different code to get it to work with the new owned trailer's. Please update us to the status of this great asset to the sim community.. Thanks

**Comment by j1m1l0k0** [comment]
Let's help David with the updated synchronizer. It is busy with work and projects and you do not have the time to upgrade the synchronizer.

**Comment by kogle130** [comment]
Probably any time after the release of Beyond the Baltic Sea..Hopefully

**Comment by DaviMedrade** [comment]
The program will be updated when I manage to purchase the new DLCs. That might take a little while still. Work should ease up over the next few days, so that shouldn't be an issue anymore.

**Comment by kogle130** [comment]
in which currency would you buy them?

**Comment by wolf0958** [comment]
Thanks for the update status David. Hopefully things will go smooth and u can update the program very soon... It is much appreciated for the sim community

**Comment by flaviel2011** [comment]
Será Que Na Proxima Att Do Euro Truck Versao 1.33 Já Teremos O Sincronizador ? A Dlc Vai Ser Lançada Dia 29 Desse Mês E Provavelmente Com A Possivel att 1.33

**Comment by wolf0958** [comment]
David. Any word if the sync program is going to be updated or is it not going to work with the current version of the sims? We are looking forward to using the sync program again. It's a great program and I as others would hate to see it not updated. Thanks in advance

**Comment by rintz** [comment]
> The program will be updated when I manage to purchase the new DLCs. That might take a little while still. Work should ease up over the next few days, so that shouldn't be an issue anymore.

Put in a donation link. 👍  I'm sure that both me and others would love to donate some money for this project. You're worth it!

**Comment by maxinnee** [comment]
please uptade!! brother 💃

**Comment by kogle130** [comment]
I was already thinking about crowdfunding:)
I will donate one dlc.

**Comment by Jxyme** [comment]
Any updates on this?

**Comment by DaviMedrade** [comment]
I managed to get the DLCs. The update should be ready in a few days.

**Comment by wolf0958** [comment]
That's great news David. Ur program has sure been missed by so many players. Thanks for the updates. Believe me we all appreciate ur work and contabution to the sim community
________________________________

**Comment by kogle130** [comment]
Lovely! Can’t wait.
Thank you David

**Comment by wolf0958** [comment]
Yes I agree. Can't wait for this great program to be updated to work with 1.33 it has been missed by so many. Thanks David
________________________________

**Comment by wolf0958** [comment]
David. Did u run into problems updating ur sync program? We are all very excited to get it functional again. Please advise us if it's possible to update to version 1.33

**Comment by alastair147** [comment]
Hey! How are we going on this? We are getting excited to this tool back into action within the VTC. Hoping that now that you have the DLC's we should be close to seeing this!

**Comment by DaviMedrade** [comment]
I just finished recreating my development environment (I bought a new computer a few months ago). Now I need to extract the game and DLC files to extract the data. This might take a couple of hours.

**Comment by alissonmss** [comment]
Thank you for the update!

**Comment by wolf0958** [comment]
Thanks for the updates David. Hopefully all goes well and the sync program will be updated and working soon. So many VTCs miss this great program. Keep up the great work and thank u again
________________________________

**Comment by DaviMedrade** [comment]
I lost the scripts I used to extract the .scs files in an organized manner, as well as the scripts I used to process game and save data to generate the job lists. I'm recreating them, but that might take a while.

**Comment by kogle130** [comment]
Ouch.
Thanks for your efforts!

**Comment by j1m1l0k0** [comment]
@davidsantos-br  precisa de ajuda em alguma coisa ?  Se quiser ajuda meu discord j1m1l0k0#2507

**Comment by wolf0958** [comment]
Hopefully all will go well David and the update will be coming soon. Ur program is great and missed by so many VTCs. Let us all know if we can help in any way. Thanks
________________________________

**Comment by Anderson-br** [comment]
Boa tarde David , não sei se o pessoal comentou, agora uma nova opção que chama mercado de carga, e a maioria do pessoal do multiplayer ansioso para usar o mesmo em sincronismo para o comboios, conheço mercado de carga podemos usar o trailer próprio, aguardamos ansiosamente pela atualização.

**Comment by DaviMedrade** [comment]
Sorry for the delay. I should be able to continue working on the update in a couple of days.

**Comment by Michl7** [comment]
Thx for the update and thanks for your efforts!

**Comment by wolf0958** [comment]
Thanks for the update David. We are all thankful that u take the time to do the program for the sim community. Hopefully all will go well and it will be updated soon
________________________________

**Comment by wolf0958** [comment]
David. Anymore updates to the progress of this great tool. We are all still looking forward to the updated release. Hopefully all is going well and looking forward to using it again. Thank you for your efforts

**Comment by Marcelokash** [comment]
obrigado cara seus esforços naos serão em vão

**Comment by Marcelokash** [comment]
obrigado por seu emprenho

**Comment by Anderson-br** [comment]
Boa tarde Davi, como anda a atualização?

**Comment by wolf0958** [comment]
David. Just wondering if this great program is going to be updated ?? It's been quite a few days since we have heard anything from you. I keep hoping that it will be updated soon and thanks for all u do for the sim community

**Comment by trooldelta** [comment]
e aí Davi blz? faz um tempo que eu usava seu sincronizador, voltei agr e soube que vc está arrumando... espero que tudo dê certo men, pq é o unico sincronizador que eu uso e sei usar kkk

**Comment by DaviMedrade** [comment]
Most of the work is done. I expect to release the new version next weekend (March 9 or 10).

I already rewrote the scripts that extract data from the game and jobs from saves (which I had lost). Thing is, SCS reworked the way jobs specify trailers. The new way is a lot better (I expect fewer “Game Change Detected” issues going forward), but it's totally different from how it was done before, so I'm having to rewrite the server-side job filter from scratch. If all goes well, it should be done by the weekend.

**Comment by kogle130** [comment]
Thanks mate!
Hope everything will work out well this time !

**Comment by DaviMedrade** [comment]
I should probably mention that syncing won't work for the cargo market because the offers in the cargo market aren't directly placed into the save.

**Comment by DaviMedrade** [comment]
Version 5.5.0 has been released.
