### ISSUE TITLE
não esta pegando este sincronizador na versao 1.32

### ISSUE THREAD

**Issue by flaviel2011** [davidsantos-br/ETS2Sync-Helper-4#39]
como o titulo já diz eu não consigo sincronizar na versão 1.32 o que devo fazer ?

**Comment by pastyle** [comment]
também já tentei de tudo, não funciona :-(

**Comment by flaviel2011** [comment]
Pois é mano

**Comment by DaviMedrade** [comment]
Duplicate of #38
