### ISSUE TITLE
Everything ok but still not synced

### ISSUE THREAD

**Issue by fuatkumru** [davidsantos-br/ETS2Sync-Helper-4#40]
Like i said. I started sync helper. Settings is ok save is ok. Clicking sync botton works perfectly. Downloading the jobs. it says sync complate but all i'm getting is normal 5 hour remaining jobs and not sycned with my friend. Can you help me?

**Comment by CiprianN23** [comment]
The software is no longer working with 1.32 update of the games
Check #38 and you will find out more.

**Comment by DaviMedrade** [comment]
Duplicate of #38
