### ISSUE TITLE
Alterações nos arquivos detectados

### ISSUE THREAD

**Issue by Grandgousier1** [davidsantos-br/ETS2Sync-Helper-4#43]
Hi,
Sempre que sincronizamos os trabalhos, o nosso camião é sistematicamente enviado de volta para a nossa garagem. Espero que nos possa ajudar!
Traduzido de francês, por DeepL

**Comment by GabrielFrohlich** [comment]
Yes, because since 1.32 the sync doesn't work. Check #38

**Comment by DaviMedrade** [comment]
Duplicate of #38
