### ISSUE TITLE
" No ETS2 profiles found "

### ISSUE THREAD

**Issue by Xox77** [davidsantos-br/ETS2Sync-Helper-4#44]
When i select my folder where are my steam profiles  , ETS2sync-helper says " No ETS2 profiles found" but i don't know why , my profiles are in the folder " steam profiles " .
Please help me .

**Comment by CiprianN23** [comment]
Because software wasnt updated to work with latests versions of the games. See #38

**Comment by Xox77** [comment]
Where can i find the update ?

**Comment by CiprianN23** [comment]
There is none. No update. Nada. Read the issue 38 and you will understand

**Comment by DaviMedrade** [comment]
@Xox77, please check if this problem still happens with the new version (version 5.5.0). If it does, please reopen this issue.
