### ISSUE TITLE
Can use cloud profiles

### ISSUE THREAD

**Issue by Nisgrak** [davidsantos-br/ETS2Sync-Helper-4#46]
I download the new version, but didn't found my profiles, all are in the cloud of the game,
Thery are in the steam_profiles, ¿it's a bug or need a update?

Thanks for the update btw :)!

![image](https://user-images.githubusercontent.com/19597708/54083388-d26fc480-4322-11e9-88b5-a8ef3acc4d2a.png)

**Comment by CiprianN23** [comment]
That might be the problem. They are on the steam cloud which means the syncer cant acces the save files 

Edit: I dont think the syncer would be able to access your steam account cloud to get the data

**Comment by DaviMedrade** [comment]
OK, I'll look into it.

**Comment by ZUKMAN** [comment]
You should try changing Info.cpp
wxDir profilesDir(mDirectory + L"\\profiles\\");
to
wxDir profilesDir(mDirectory + L"\\steam_profiles\\");
and see if it works.

**Comment by EduardoVR97** [comment]
Também estou com o mesmo problema após utilizar o Steam Cloud no save do ETS

**Comment by xeiki** [comment]
is there a chance that would be fixed anytime soon?

**Comment by xeiki** [comment]
I found a solution for this cloud thing.
Just deactivate it in ETS2 and on Steam himself.

I created a little screenshot tutorial if somebody has trouble with how disable steamcloud in ETS2.
Follow this introductions on here: https://ets2-sync-fix.github.io/#english <--

**Comment by volvogamesgyn** [comment]
The friend eikichi87's solution worked, now it is expected that SyncHelper will work with the steam cloud (although it seems complicated, as it would have to have access to the steam account in question), as I have already lost many saves (for various reasons) for not have enabled this steam option.
