### ISSUE TITLE
ERRO DE INCOMPATIBILIDADE 

### ISSUE THREAD

**Issue by Anderson-br** [davidsantos-br/ETS2Sync-Helper-4#47]
SINCRONIZEI DE TODAS AS FORMAS, E MESMO ASSIM DEU ERRO DE INCOMPATIBILIDADE. ASSIM SENDO VOLTA PARA GARAGEM

**Comment by DaviMedrade** [comment]
Quais DLCs você tem?

Aparece alguma mensagem relevante no console?

**Comment by Balcru** [comment]
Ami me pasa lo mismo que Anderson, al intentar cargar el archivo sincronizado el camion vuelve al garaje principal, se pierde la sincronizacion y me aparece el siguiente mensaje:

"Advertencia se han detectado cambios importante en juego , para evitar problemas  al guardar la partida debido a un cambio en el mapa del mundo, todas la entregas pendientes han sido canceladas sin penalización alguna."

la consola indica lo siguiente:
00:08:03.682 : Garage update finished.
00:08:03.839 : [actor] Initialized at [-3006.4;36.2;-4182.6]
00:08:03.840 : [actor] Teleported from [-3006.4;36.8;-4182.6] to [-3006.4;37.0;-4182.6]
00:08:08.070 : Incompatible save game loaded.

Al parecer ETS2 no es compatible con salvado en formato de texto desde la versión 1.33
ya que e usado otro sincronizador de trabajos "Virtual Speditor" que salva en binario y no e tenido problemas de sincronizacion, pero me gusta mas tu programa, ya que tiene un uso mas amigable y sincroniza todos los trabajos, no como Virtual Speditor, que solo sincroniza un trabajo solamente.

Saludos desde Chile.

![ets](https://user-images.githubusercontent.com/48415592/54089594-4ae97c00-4349-11e9-9074-2dbfa12b262b.jpg)

![ets1](https://user-images.githubusercontent.com/48415592/54089654-ebd83700-4349-11e9-9a49-891b9b507af5.jpg)

![ets2](https://user-images.githubusercontent.com/48415592/54089655-eda1fa80-4349-11e9-952d-7b382915e9a6.jpg)

**Comment by Anderson-br** [comment]
> Quais DLCs você tem?
> 
> Aparece alguma mensagem relevante no console?

Tenho todas dlcs, sincronizei com elas todas, depois fiz o teste sem, e também fui marcando uma por uma, mais infelizmente deu incompatibilidade e voltou para garagem, no console não observei.

**Comment by Anderson-br** [comment]
![05](https://user-images.githubusercontent.com/28768276/54091378-2c41b000-435e-11e9-8a26-03bc74e49d61.png)
![02](https://user-images.githubusercontent.com/28768276/54091379-2c41b000-435e-11e9-946c-16d2ae6ae482.png)
![03](https://user-images.githubusercontent.com/28768276/54091380-2c41b000-435e-11e9-9197-7cc0f2095888.png)
![04](https://user-images.githubusercontent.com/28768276/54091381-2cda4680-435e-11e9-8233-5f377b4512e7.png)

**Comment by DaviMedrade** [comment]
Essa mensagem significa que ele não encontrou o trailer “caravan”, que é fornecido pelo TruckersMP. Você iniciou o jogo pelo TruckersMP? Note que a sincronização não funciona em modo single-player (offline).

**Comment by Anderson-br** [comment]
Correto, Acabei de testar aqui agora e funcionou no modo Multiplayer.
Nos modelos anteriores ele funcionava também   no single play. sendo assim está ok.
