### ISSUE TITLE
onde baixar a versão atual 

### ISSUE THREAD

**Issue by flaviel2011** [davidsantos-br/ETS2Sync-Helper-4#48]
como na descrição estou tentando baixar a nova versão

**Comment by Anderson-br** [comment]
http://files.dsantosdev.com/ets2sync_helper.zip

**Comment by flaviel2011** [comment]
não consegui

**Comment by DaviMedrade** [comment]
O link tá funcionando, então se você não conseguiu deve ser algo relacionado ao seu computador ou à sua conexão. Sem mais detalhes fica difícil diagnosticar o problema específico.

**Comment by flaviel2011** [comment]
eu faço o procedimento correto quando eu vou carregar eu volto a minha garagem com uma mensagem de detecção

**Comment by DaviMedrade** [comment]
Você sincronizou no multiplayer? No single-player não funciona mesmo.

**Comment by flaviel2011** [comment]
Sim Tanto Em Um Quanto No Outro

**Comment by DaviMedrade** [comment]
Então por favor envie o seu game.log.txt (fica em Documentos\Euro Truck Simulator 2 ou Documentos\American Truck Simulator) ou um print do jogo mostrando as mensagens de erro no console.

Para anexar arquivos aqui, você pode clicar na mensagem “Attach files by dragging & dropping, selecting or pasting them” na parte de baixo da caixa de texto onde você escreve a resposta.

**Comment by flaviel2011** [comment]
[game.log.txt](https://github.com/davidsantos-br/ETS2Sync-Helper-4/files/2977273/game.log.txt)
![ets2_20190318_062439_00](https://user-images.githubusercontent.com/43672235/54520160-d3b67800-4946-11e9-8a92-2099c34d1850.png)

**Comment by DaviMedrade** [comment]
```
The unit '_nameless.dcc.f190' of type 'job_offer_data' has dangling pointer (to 'cargo.caravan') in the attribute named 'cargo'.
```
Essa mensagem no game.log.txt significa que você não sincronizou no multiplayer.
