### ISSUE TITLE
American truck simulation 1.34 will be invalid, hope to be updated

### ISSUE THREAD

**Issue by WildBoyHJ** [davidsantos-br/ETS2Sync-Helper-4#49]
美国卡车模拟1.34会失效，希望可以更新

Google Translate：America truck simulation 1.34 will be invalid, hope to be updated

**Comment by DaviMedrade** [comment]
I'll need more information. If you are experiencing an error after syncing, please attach your game.log.txt (from Documents\American Truck Simulator).

**Comment by wolf0958** [comment]
David. When we try to sync it puts us back at home garage and sync doesn't work.

**Comment by wolf0958** [comment]
Forgot to mention this is in multiplayer. I know it doesn't work in single player. Even after following correct procedure still get same result. Last version worked great till the new updates from SCS. Could this be something with the code missing

**Comment by WildBoyHJ** [comment]
When we try to sync it puts us back at home garage and sync doesn't work.I don't know how to upload the log, but the European Truck Simulator 2 can be successfully synchronized.

**Comment by wolf0958** [comment]
Right. I agree with the above post. This happens in ATS

**Comment by DaviMedrade** [comment]
Under the box where you type your reply, click on “Attach files by dragging & dropping, selecting or pasting them.” and you can attach files. Another way of providing the information is by attaching a screenshot of the game console right after the problem happens, preferably showing the red error messages.

**Comment by wolf0958** [comment]
David after syncing in ATS we all just get the message ( Changes have been detected and truck has been moved to a safe place ). This would be our home garages. This happens after syncing. When we go to check sync it does not work as all loads are not the same. Even the time loads expire dont match. Loads should have times like 400 hrs but still show for example 21 hrs

**Comment by WildBoyHJ** [comment]
This is my log, the game screenshot, the interface may be Chinese, but probably can understand what the problem is, after syncing in ATS we all just get the message ( Changes have been detected and truck has been moved to a safe place ). This would be our home garages. 

[game.log.txt](https://github.com/davidsantos-br/ETS2Sync-Helper-4/files/2976015/game.log.txt)

![ats_20190318_091736_00](https://user-images.githubusercontent.com/22376209/54501232-010f2000-495f-11e9-89e8-4e8f097aeda7.png)
![ats_20190318_091638_00](https://user-images.githubusercontent.com/22376209/54501233-010f2000-495f-11e9-8a7a-96c7c91a5d93.png)
![ats_20190318_091715_00](https://user-images.githubusercontent.com/22376209/54501234-010f2000-495f-11e9-8c9d-0b1e899a2495.png)

**Comment by DaviMedrade** [comment]
Thanks. Now I know what the issue is. On List 8 there is a job from Albuquerque to Alamogordo which the job filter on the server detects a need to change the trailer, and changes to one that the game doesn't accept for that cargo. I'll see if I can figure out what the job filter is doing wrong.

**Comment by WildBoyHJ** [comment]
Great, know the problem, then you can try to fix it. It’s hard for you.

**Comment by DaviMedrade** [comment]
I updated the filter, and after syncing with the updated filter this problem did not happen. The new filter is already live on the server, so you don't need to download an update. Just sync normally and it should work now.

**Comment by wolf0958** [comment]
Great job David. ATS now syncs properly. Thanks for all ur work u do for the sim community
