### ISSUE TITLE
When will the 1.35 version be updated?

### ISSUE THREAD

**Issue by WildBoyHJ** [davidsantos-br/ETS2Sync-Helper-4#51]
Hello David Santos. When to update Euro Truck Simulator 1.35 and American Truck Simulator 1.35, and the latest Washington DLC

**Comment by DaviMedrade** [comment]
Either this weekend or sometime next week.

**Comment by wolf0958** [comment]
Glad to hear it will be updated to new version of 1.35. TMP updated yesterday. This is a great tool David. Hopefully u won't have many problems updating it like the probs you had with last version. Looking forward to using it for Washington state with friends. Keep up the great work

**Comment by Anderson-br** [comment]
Boa tarde David, na nova atualização foi implementado o mercado de carga externo no World of Trucks,  sei que da última vez que Você atualizou teve algum problema relacionado a isso,  a maioria do pessoal que usa o seu sincronizador tem a expectativa de usar ele fazendo sincronia  com o trailer próprio.
 talvez com essa nova atualização você consiga descobrir alguma coisa diferente relacionado a isso. desde já agradeço pelo empenho que tem em manter o programa Sempre atualizado. mais uma vez parabéns pelo seu trabalho.

**Comment by DaviMedrade** [comment]
Version 5.6.0 supporting 1.35 and the new DLCs has been released. No support for the cargo market or Steam Cloud yet.
