### ISSUE TITLE
ETS2 1.35 nao sincroniza mais

### ISSUE THREAD

**Issue by xdmonster** [davidsantos-br/ETS2Sync-Helper-4#52]
![20190621105238_1](https://user-images.githubusercontent.com/52076742/59928134-73871480-9414-11e9-807f-5e196255355e.jpg)

**Comment by DaviMedrade** [comment]
Você estava no multiplayer? Sincronizar no single player sempre dá essa mensagem por causa das cargas de caravan.

Se você estava no multiplayer, apareceu alguma mensagem de erro no console? Você pode tentar carregar o save sincronizado novamente e anexar aqui o arquivo `game.log.txt` da pasta `Documentos\Euro Truck Simulator 2` (nesse arquivo já teriam as mensagens de erro que aparecerem no console).

Pra anexar o arquivo é só clicar nessa mensagem que diz “Attach files by dragging & dropping, selecting or pasting them” na parte de baixo da caixa de comentários.

**Comment by wolf0958** [comment]
David. Thank you for always keeping this great tool updated and your dedication to our community. All is working great in ATS version 1.35

**Comment by Michl7** [comment]
Thank you David for the fast update. Works great in ETS2MP. Greetings from Austria.
