### ISSUE TITLE
download versão 5.6.0

### ISSUE THREAD

**Issue by JanorTeotonio** [davidsantos-br/ETS2Sync-Helper-4#53]
não to conseguindo baixar a versão nova, o link do site faz o download da versão 5.5.0

**Comment by DaviMedrade** [comment]
Acabei de verificar os links que eu uso e estão com a versão 5.6.0.

Qual link você está usando?

**Comment by JanorTeotonio** [comment]
este aqui http://files.dsantosdev.com/ets2sync_helper.zip
que esta na neste pagina https://github.com/davidsantos-br/ETS2Sync-Helper-4/blob/master/README.md ao qual o próprio aplicativo me direciona

**Comment by DaviMedrade** [comment]
Testei esse link mais uma vez e veio a versão 5.6.0. Pode ser alguma questão de cache.

Em todo caso, também dá pra baixar daqui:

https://github.com/davidsantos-br/ETS2Sync-Helper-4/releases

**Comment by DaviMedrade** [comment]
Alterei os READMEs para usar a página de releases do GitHub como fonte oficial do download.
