### ISSUE TITLE
where do i get the new version

### ISSUE THREAD

**Issue by Jeremy299** [davidsantos-br/ETS2Sync-Helper-4#54]
it says theres a new version i go to download the file and it opens the application but it doesnt say 5.6.0 it says 5.5.0 still everytime whats wrong?

**Comment by DaviMedrade** [comment]
That's odd, because I just tested the link (again) and it was 5.6.0.

In any case, you can download from here as well:

https://github.com/davidsantos-br/ETS2Sync-Helper-4/releases

**Comment by DaviMedrade** [comment]
I've updated the README files to point to the GitHub releases page for the downloads instead of the copy on my server.

**Comment by Jeremy299** [comment]
Ok thank you I’ll try
