### ISSUE TITLE
Mercado de cargas

### ISSUE THREAD

**Issue by imjosephe** [davidsantos-br/ETS2Sync-Helper-4#56]
Olá, só gostaria de perguntar se usando o ETS2Sync Helper é possível sincronizar o mercado de cargas, se não, algum dia vai ser possível ou não? Aliás, parabéns pelo projeto.

**Comment by DaviMedrade** [comment]
A menos que a SCS altere a forma que as cargas do mercado de cargas são armazenadas no save (o que não acho muito provável), isso não vai ser possível.
