### ISSUE TITLE
suporte versão 1.36

### ISSUE THREAD

**Issue by JanorTeotonio** [davidsantos-br/ETS2Sync-Helper-4#59]
previsão pra suporte a versão 1.36 com a nova expansão de mapa?

**Comment by wolf0958** [comment]
David. Was wondering if the Sync program is going to be updated to support version 1.36?? Thanks

**Comment by wolf0958** [comment]
David. Was wondering if the program is going to be updated to support version 1.36 or is the project dead in the water now..
