### ISSUE TITLE
Compatibilidade com ATS e DLC Vive La France!

### ISSUE THREAD

**Issue by DaviMedrade** [davidsantos-br/ETS2Sync-Helper-4#6]
Como o ets2sync.com saiu do ar, tive que dar um jeito de gerar uma lista de cargas. Com isso, só preciso fazer algumas adaptações para que o programa suporte o ATS e a DLC Vive La France!

Assim que eu tiver um pouco mais de tempo, faço essas alterações.

**Comment by FOX-TROT9993** [comment]
O meu ets2_Sync_helpe já esta fazendo o sincronismo, não ta dando mais aquele erro 503 Temporarily Unavailable , só que quando entro no jogo e mando carregar o save as cargas estão todas dessincronizadas  todos com horário diferente,tem alguma coisa errada poderia me ajudar?

**Comment by DaviMedrade** [comment]
@FOX-TROT9993, tente com a nova versão. Se não funcionar, abra outra issue.

**Comment by DaviMedrade** [comment]
v4.1.0 suporta a DLC da França; v5.0.0 suporta o ATS.

**Comment by davidsantos-br** [comment]
v4.1.0 suporta a DLC da França; v5.0.0 suporta o ATS.
