### ISSUE TITLE
Version 1.37

### ISSUE THREAD

**Issue by gaborka98** [davidsantos-br/ETS2Sync-Helper-4#61]
Please update to support version 1.37

**Comment by krmrbtn** [comment]
Finally i found someone who has the same problem!

**Comment by Frorran** [comment]
This hasn't been updated since a year back. I'm starting to question whether this is still being worked on or not...

**Comment by padilhakil** [comment]
cade a versão 1.37 ou 1.38 
andem logo com isso

**Comment by Inklay** [comment]
I forked this project and I'm currently adding 1.37 and newer support, you can go here https://github.com/Inklay/ETS2-ATS-Sync-Helper if you want the latest update

**Comment by gaborka98** [comment]
> I forked this project and I'm currently adding 1.37 and newer support, you can go here https://github.com/Inklay/ETS2-ATS-Sync-Helper if you want the latest update

I need to compile to myself or you can upload compiled exe to releases?

**Comment by Inklay** [comment]
> > I forked this project and I'm currently adding 1.37 and newer support, you can go here https://github.com/Inklay/ETS2-ATS-Sync-Helper if you want the latest update
> 
> I need to compile to myself or you can upload compiled exe to releases?

I will upload a compiled exe later today, I still need to work a little bit more on it

**Comment by Inklay** [comment]
> > > I forked this project and I'm currently adding 1.37 and newer support, you can go here https://github.com/Inklay/ETS2-ATS-Sync-Helper if you want the latest update
> > 
> > 
> > I need to compile to myself or you can upload compiled exe to releases?
> 
> I will upload a compiled exe later today, I still need to work a little bit more on it

I published a beta version of the exe, I didn't have time to test every job list, if you encounter an issue please let me know it. I don't have any job list for ATS either, I'll certainly make them tomorrow

**Comment by IgorSanj** [comment]
when the program starts, writes about the missing files MSVCP140D.dll, ucrtbased.dll, CONCRT140D.dll, VCRUNTIME140D.dll.
I found out that the suffix "D" in the name of the dll means that the Debug version is used. These versions are not included in the Visual C / C ++ Redistributable. So the first thing that follows to do - rebuild your application in the Release configuration.

**Comment by IgorSanj** [comment]
when I press "sync jobs" it writes an error "InternetOpenUrl error 0x00002EFF". Tried it yesterday and today. Nothing changed
